# Generated by Django 4.0.5 on 2022-10-04 14:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('a', models.TextField(max_length=200)),
                ('b', models.TextField(max_length=200)),
                ('c', models.TextField(max_length=200)),
                ('d', models.TextField(max_length=200)),
                ('alternative_correct', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questionmodel')),
            ],
        ),
    ]
